### ISSUE TITLE
Single file Uri without list

### ISSUE THREAD

**Issue by buildbro** [onimur/handle-path-oz#1]
Thank you for this library.
Your documentation and sample app seem to only make reference to multiple files (list). I will love to see how you recommend I implement this for a file picker than will only pick one file.

**Comment by onimur** [comment]
I appreciate the feedback.

I chose to use only lists to reduce the amount of methods, leaving the library cleaner.

These methods are for both multiple uri's and just one. I would recommend the same usage it contains in the example. Since you are working with only one uri, you would receive a list with only one element.

If you think you are confused to understand let me know that I update the documentation and sample application, adding the use of just one file.

If you have any suggestions to add to the library or to change, I would be grateful to know.

**Comment by onimur** [comment]
@buildbro Hello, 
Have you made any progress?
Any suggestions or questions you have, I will be happy to help you.

**Comment by buildbro** [comment]
> @buildbro Hello,
> Have you made any progress?
> Any suggestions or questions you have, I will be happy to help you.

Thanks for your response. And yeah I made progress.

**Comment by onimur** [comment]
@buildbro It really was a little confusing for anyone working with a single uri. Sorry for the delay, but this project runs in parallel with my other projects.

This week I will add methods to work with just one uri. I will put it in the readme and update the sample application with the demo.

As soon as I'm done, I'll mark it here.

**Comment by onimur** [comment]
As soon as version 1.0.7 is published, the readme will be updated with the methods referring to the pull request.

**Comment by onimur** [comment]
@buildbro. 
Published version 1.0.7 and updated readme for use with a single uri.

I hope the documentation helps you. If you need anything, I'm at your disposal.
